theme: jekyll-theme-tactile
#title: Seminarios de Astronomía
github: https://github.com/seminariodeastronomia/seminariodeastronomia.github.io
about: Seminarios de Astronomía Universidad de los Andes (Colombia)
avatar_url: /imagenes/seminarios_logo.png
