theme: jekyll-theme-slate
title: [Seminarios de Astronomía]
description: [Bienvenidos a la página de los seminarios de Astronomía que tienen lugar en el Departamento de Física de la Universidad de los Andes, Bogotá-Colombia]
